from feedback import OPINION_PRAISE, OPINION_ISSUE, OPINION_SUGGESTION, OPINION_RATING, OPINION_BROKEN, OPINION_TYPES

def opinion_types(request):
    return {
        'OPINION_PRAISE': OPINION_PRAISE,
        'OPINION_ISSUE': OPINION_ISSUE,
        'OPINION_SUGGESTION': OPINION_SUGGESTION,
        'OPINION_RATING': OPINION_RATING,
        'OPINION_BROKEN': OPINION_BROKEN,
        'OPINION_TYPES': OPINION_TYPES
    }
